name: SOOS SCA Integration Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}
      SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        run: mvn -B test --file pom.xml